[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "localization-tool"
version = "0.1.0"
description = "A tool to auto translate and synchronize with Google Spreadsheet"
readme = "README.md"
requires-python = ">=3.8"

dependencies = ["gspread>=5.0.0", "python-dotenv>=1.0.0"]
